priors:
  min_coverage: 20
  eps: 1.0e-09
  max_iter_mle: 500
  tol_mle: 1.0e-08
  n_example_snvs: 6
  heteroskedastic_phi: false
  downsample_points: 10000
  data_root: data
  results_root: results
  seed: 12345
